### ISSUE TITLE
Date Formatter for rendered date

### ISSUE THREAD

**Issue by thejohnjansen** [CreaturesInUnitards/mithril-datepicker#10]
After I pick a date, I would like two things:
1. It should be automatically formatted like it is but with commas
2. I should be able to pick some formatting options (of course allowing European formatting, for example, would mean changing up the picker as well, so I know it's more work than it sounds)

**Comment by CreaturesInUnitards** [comment]
Actually, that could be a simple whitelist of possibilities. Probably wouldn't be more than 1k. I just need the list of possibilities

**Comment by CreaturesInUnitards** [comment]
ok, went with the emerging ```Int``` api, sort of. Check the README for how-to.
