### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by thejohnjansen** [CreaturesInUnitards/mithril-datepicker#11]
Since you opened an issue about accessibility, I'll log the next one about localization. I want LUNES!!!

**Comment by CreaturesInUnitards** [comment]
dude, what do you think "i18n" means? #1

**Comment by StephanHoyer** [comment]
i18n => `Montag` for `monday`
l16n => `28.03.2017` for `2017/28/03`

**Comment by CreaturesInUnitards** [comment]
Whoa, is that true? I've never seen "l16n" before... 
You're saying ```Internationalization != Localization```?

**Comment by CreaturesInUnitards** [comment]
@thejohnjansen @StephanHoyer 
Question for you:

Can you think of any reason why, in any given app, you might want multiple datepickers, each with a different i18n? Like one is English and another is Spanish?

**Comment by thejohnjansen** [comment]
Do you mean where one renders in English and one in Spanish at the same time? Maybe, but that would be a very edge case. I don't remember seeing it ever. Being able to switch makes sense to me (you think I want English, but I actually want Spanish).
