### ISSUE TITLE
Unusual `eval` call

### ISSUE THREAD

**Issue by dead-claudia** [CreaturesInUnitards/mithril-datepicker#18]
I found a [very unusual (and unnecessary) `eval` call](https://github.com/CreaturesInUnitards/mithril-datepicker/blob/master/mithril-datepicker.js#L337-L339). This makes it unusable in CSP contexts as well as minified code, since those variables can't be minified. It's also trivially substituted for its own variables, and literally takes the same number of lines.

**Comment by CreaturesInUnitards** [comment]
Smarter coders than I would leave comments over things like that to remind themselves why such a weird thing was included in the first place. Alas, I'm myself, and did no such thing. I have no idea whatsoever what scenario I ran into that "necessitated" this ```eval```. That said, I'm not sure what this means, actually:

> It's also trivially substituted for its own variables, and literally takes the same number of lines.

...so a PR would be greatly appreciated :smile:

**Comment by dead-claudia** [comment]
@CreaturesInUnitards 

> That said, I'm not sure what this means, actually:

[I meant it in the most literal way possible.](https://github.com/CreaturesInUnitards/mithril-datepicker/pull/19) 😉
