### ISSUE TITLE
Selected date cannot be updated during redraw

### ISSUE THREAD

**Issue by shipstefan** [CreaturesInUnitards/mithril-datepicker#20]
If you update the date during a redraw the date doesn't get updated but stays the original one. The view should check for a updated vnode.attrs.date and then update the vnode.state.date property.

**Comment by CreaturesInUnitards** [comment]
sorry, I don't know what you mean by "during a redraw". Could you please post some example code to illustrate? (maybe start [here](https://flems.io/mithril,mithril-datepicker))

**Comment by shipstefan** [comment]
Sorry for the copy. I didn't really gawk flem.io.

I want to update the date-attribute via an m.redraw() call because I read the date from a database.

Perhaps there is another way to do it correctly but I would check for a new vnode.attrs.date during the view-method.

```javascript
var date = new Date()

var App = {

  oninit: function() {
    // this should update the year of the Datepicker to 2000 after 100ms
    setTimeout(()=> { date.setYear(2000); m.redraw() }, 1000 )

  },
  view: function(){
    return [
      m('style', '.wrapper{padding:10px}.description{display:inline-block;padding: 0 10px}'),
      m('.wrapper',
        m(DatePicker,{date:date})
      )
    ]
  }
}

m.mount(document.body, App)
```

**Comment by CreaturesInUnitards** [comment]
Sorry, I believe your use case is an anti-pattern; if your DB response is slow you might actually interrupt your user in the middle of using the datepicker.

A better approach would be to only show the widget when the date object is available, [like this, for example.](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvEAXwvW10QICsEqdBk2J5YxAARYAngBEMjCQF4JaAK5QoAHTTiJYGMWqEIaAObL9GKHBg6dQuJINHC8xSoAUASmUA+CWAdCX1DY1MLFWIAJzU7NBDbYgAVCBxaNWJPH39AqTkFGEs0GAB3CXcYHwBuKXxomAATaIxSnPYJAEYABl7vHVZ7NEdJAGFaLAAHehFLIISJADcIMsQJHKUArE8Ach2KYJCJAEIZSokAMgupXYAjTOJ6fYlDo7zXt4lGiDgMW9hGmsXOFzAcFp8JPRqFAINQANZAsJuQovcFHDofELAkzmCQAfgkO2xEXwpJ2EjWRKREgwX0KOw+3jBbzOKKuN0qAAVYXCYNEKIFGoU1qzGKx+gsJYM0DosPgsBkGJ5GrRqGocAx8LdaI1pALxlMZgxvJQaBNJtA+Xhbn8YOQqLZYNRiBB6AgeAAmTqIADMPrYHBAmBweHw1DgAjNwmYPAA9AAqRNJ5Mp1OJiQAOQA8hIAKoAZQAogAlAC0ReLADUAJKjQsAQQAQgAZQsSTn14vJfMSasZ-PV2RttMjtMSeOxnQJ0cz2dz+cL0fjydoeUQYiEaLQUtCxili3wvmloTEDCmPmBQ7TODr11oNYNKAKCCLGDVQ7fOCTJ-SNamGElKW-yqnC74LAAXqWpiNDAAAeazdLU0ohGuG5blAO6FPuPJHieZ4lNE+AYM6L5FPMbyQdBcFrAAnHRdFIUMqGbtuu4wNhh78hIzHoZhe4Hry0TjpeCzarBpY3uBERrNq0QwdEQG0LBYEhKWpQwLccLrqWai2ApjowM6axoDMKkSKWCqQbpR4GUZqimYcFlwDpekSXahnEMZDkLNZ+nuXZJklIxMqrlg64sRhbEcYJIkhFgGDRGYpgIRIAAskzKRIyHcWFaGsVhAkXvGAo8fl-E4UJ9zEI8CTkUcYD0MQpZgNg0C-hIWaTC68UCgAEnar4utQGACvWW7WAKvxoM5ekQGAZkhBkxAATAXlBR8kwYI03zmAhwUoblEV8exhVCWGajRA0DDHbFRzXre9APnaz6vgtEilBAjQbmsPrdAAHBlb02vCZjRIqgISAAxDAMOw0DtByXye0fHQUAI2skMAKzYzjb2bdt0ldN0gMfA112SatEgeh6JNoowsFNdYEBmPeEjUCIfJvWq0RwOjEjTKYjDRG9lFoDB8FdPtOXhbxUWndxtCvtEP63SE90uo9+gQLBTRvY8kzI2isBgJ5EiIR8H1fYQaw9N0iylG9hAwMzJA270iyEEDxFwqD4MPmYNqeB62MCsHmOhyHZv4H93hS6VkUFRV3GmHQYW4nVi2bdQ67tYhWWHPHx3RRe+BNOuCOq-ztA3hrrN-LzUCZG+HzxYlyVm2ltNvPrhtvMbpvm2ilvfRIv0A8pHxOy7A96y000PazU9mCQUcenAItQWL1GSx8it8mAaOlGsJjbUwUsHTLZUnUnpffI8hHES6r6VyES+u6PmMAOz4D6NGA-nCxC5yxvk7LaF4M5VxrneJ6T4n7NzRJ+b8GB2oHzgm9XgukXRgGkMeRqIg1hfmIuxW4hh1Jnw+MDH2YM1BiwxtTehHp4aIwUi0b4uk1jpQnmiVuSU0CKWqhMDh-9soXzygncqnFuKgPkhIKqNUX6QIXjAl68CIT4x2mYXunweHt0HhCN+ptUqcLeiEShvsaEQ0Cqoz4sl5JaLeNzXm0Q1gC2EMLABbwgGJ0kUQGAYDKoPHoPgSYDRFglUOrLbxMVfH+NkYE1cJQGYKLTmpT6I8jFd0+GTJqFMbapXwAANiKQUz+mSHG0DRs496JhGAmOqeudihD2ZeVKC0SY58jheIkdE6RF45FBJCTARYiAMAmz5OEy+4jr4+N6QEgRCS4KeVGULBRIQTz4JeCALQIA6lq2rkomktwG5N12RIHubNrDUE8JjboABScyEgCn4ExhlWOmIjjD2tl0ToZTPgGJtj8rhEJTEI3kqWc5NNYISAbp9eptT3kguYaWLcy9TaQuhRU2FpQalvg8Z0iJV9i5nVmXE+ZwTQkKPpozGELM1j9zqeoiIpZ+422-gU35cUEq8ORdPNYGBMi0A6aIo6wCZl+Jkf01cgzhnLPAQiqQXLTDMpgCbNY39ujGPlTovhKL378seKcllZtTkxAwNNBq0QsAPloKeRgnhSydB9JjGCZhY54uFZE7pJcSWSvwIkyQECQhUtLEzWlEhdXEAZVtDRPLUWssKRyhVbc+FGv1YK91+LJlF3ljEiV8S-WLJGWMoSgajjatje-dVmq0QskVSmlVps02nIjfYz4przUIyteGm1hRPCpWdTAV1HSunTJ6eKkukqgIWFLeraBhzjnwprWc2gBsJA3NuXU9tcALVdq3bAmAABNe1663lLs+WsApPof5+j9Im-5Eg-p3LqWY6htCob0XopuueUDNbdHwGvIV0sxHZpAeOs6k7bhmHwIsboqyJBGsxn-IFwLbFHn1sqk2yKtoQHYV0dlyGISoYUtqARWAMNNVYThuANt8OAZHUSqRYHuIQag4sTocGjWdGptem9ibEVgso7hvOIjM3AdFWO2JWp4lTugx6DjDabZ-UxoU4ppSCM2NBWhldFaKPYdw50Wj8qiP8MeGRiNWG2HUbw8Ij49Gc0kvwC1XkilmEKNnZreuFSTnvIQ0+955z111PPV0GixN1Ov2dnGh9fml1bp3WsPdvbSzroFMlu5p7COaaqYCjFMJGjvo-TRZ9WWLNUZozZtEdnQOSdsGYDUAb3nudZo+FRQW0lfMvTx294W2YVL5tihpdTskSQgOBSmnQaLPJxrRvFVWfFwABJXJryi4FvUQT+IEsB1PBd+jF7u36Dnlv7qvdeGa5vRIW00YJsHS1HYU8as7BKpkMfwJdxowT2O3breRtYDregbse1m8TJc3vBLk195NP3zIen+3HJ7IGfHDVgGLBKldjOCas9Wt4y3w3PVW7vJWB9aBHwkCfGCaA3o7f+r80W4s9qzfh8Ds6ZC4RCmkHACZYmoklwVAwQgcBK7reQZttBpMttqTaWsVpGB2kM6B9zs6bPOcioVzlRqhBleetHSXaQfiS0bX2bXFbpE3rDdyV0NlvyX1+yhrDOGFCsuttRnzLGONsZcwuk4lxtBBacw+LT7ewnbOM9V-gNniAGpqg50BlXXqzq8++pH3SmvCU5t1wlCPqpdIKIDxLTow6Q9x+4uHwge8uLnZ5+rxApelYp+e2nvX1ey8KOtxYjGjRnWd4L-LovYfkFh-VDIOvCPokJ8IAPrAQ+Y9a5e+nwijRB-SBb97cxb7IY3pvXU53VSBuLsy8w1tazPd8xgi1DQkb3lC5QVtupGCnBzRweshgax2ZuLqaGvhDSsBWdf0LOjhftdFd+8F9J9fwa9xlp9U8b4x8J8ZAm9a9ID68b459YCwDm9S1TEV9X0IZ18N8fRu8ude82duJ1AsASFy8ACXsx8SD1RyDh8mduI58aCyC5Ul0ccWt8cl1c8bYCDY9ADi9+9jBq4mB6DQ8YChDbA0BRDe8UCJCmBl8QZsCpccVisD8qYMpctYVcCN8htGo1JItK1eg4ce9+C+8l8IFgsMl1N70rDjDCDTDqCLD2s1hg4N1J4DDTZP41M7C+DZ89dK5gsYc3C0R70ClOgE1MpsoK8zobUnZ9I6BJgyIUY+sqlIZCsisspTRbJa53QQAJsPREAvQ2AABdKgACOEd0VAIMLgPAJ7U0C6cgHgEgYgSYajWMWMGhSYH2MMCYWMJ7AAAXCPCIKT6MmXwH4FNGIGkESLwAmPYE4BDB4AANOnqOVjwGaNaMQHaM6O6NTlGPsNOn6L-Umw9H2L4NOnGMjCmJmJ4DmMDGDG4BACcGkFgDDAjFWMaJAA2LaNjBaFKHwCSg3DUHuD0if2IB6KwFjFGAaAUAungGrDQFzDQHXASkaDgDOK11Oj6IwCcD5FjDgGiGoHxKmNePDCuOmMeLJJKNYCAA)

**Comment by shipstefan** [comment]
Thank you very much. Your example helps a lot. 

I thought conditional execution was an anti-pattern itself but I was wrong.

**Comment by CreaturesInUnitards** [comment]
@shipstefan no problem! Please let me know if you think of any other way I can improve this. Thanks!
