### ISSUE TITLE
omit sass depencency

### ISSUE THREAD

**Issue by StephanHoyer** [CreaturesInUnitards/mithril-datepicker#5]
would be great to be able to use this without webpack/browserify plugins

**Comment by CreaturesInUnitards** [comment]
I'm trying to figure out the best way to make this skinnable. Certainly just changing the values at the top of the sass file is fast; alternatively any dev could simply change ```.sass``` to ```.css```. Suggestions about a better mechanism are more than welcome, thanks!

**Comment by StephanHoyer** [comment]
Adding a sass file to the repo is ok I think. But requiring this in the js file is sub optimal. Why not just leave the style integration up to the user.

**Comment by CreaturesInUnitards** [comment]
Ah, gotcha. Ok, simple enough. I’m in the middle of a sizable refactor, so that’ll be pushed tomorrow probably. Thanks for your help.

**Comment by StephanHoyer** [comment]
ok cool

wanted to add some tests. I'll better wait with that :)

**Comment by CreaturesInUnitards** [comment]
Outstanding! That'll be a tremendous help — I am the headless chicken ATM, and would love to spend 10 straight hours working on this thing properly, but that ain't gonna happen. Thanks again.

**Comment by StephanHoyer** [comment]
I always planed to do something like this. Two of my projects use pick-a-day atm. It's heavily over engineered and I would replace it with something mithrilesque.

**Comment by CreaturesInUnitards** [comment]
Ok, that's done. Hack away, please!
