### ISSUE TITLE
UI: datepicker header slightly extends past body

### ISSUE THREAD

**Issue by pakx** [CreaturesInUnitards/mithril-datepicker#7]
see item labeled "border width ?" in attached screenshot

![datepicker-header-offset](https://user-images.githubusercontent.com/19353048/28226001-83e5b9d4-68a2-11e7-98b1-c5e96fc5c640.png)
screenshot

**Comment by CreaturesInUnitards** [comment]
I saw this in Firefox only in previous iterations, fixed now for me. Please confirm.

**Comment by CreaturesInUnitards** [comment]
No longer repros, I'm closing this.
