### ISSUE TITLE
datepicker does not "reset" view on invocation

### ISSUE THREAD

**Issue by pakx** [CreaturesInUnitards/mithril-datepicker#9]
I would expect each invocation of the datepicker to default to its standard view (#2 in attached img); rather it seems to retain last-viewed state.

![datepicker](https://user-images.githubusercontent.com/19353048/28226517-6a67b910-68a4-11e7-97c3-6e3f64e24edb.png)

**Comment by CreaturesInUnitards** [comment]
yup fixed, thanks.
